function ConvertTo-RBAC4AppYaml {
    param(
        [Parameter(Mandatory)]
        [psobject] $Config
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# RBAC4App configuration — generated by New-RBAC4AppConfig')
    $lines.Add('# Feed to Invoke-RBAC4AppConfig in a session with only ExchangeOnlineManagement connected.')
    $lines.Add("SchemaVersion: `"$($Config.SchemaVersion)`"")
    $lines.Add("GeneratedAt: `"$($Config.GeneratedAt)`"")
    $lines.Add("TenantId: `"$($Config.TenantId)`"")
    $lines.Add('')
    $lines.Add('Application:')
    $lines.Add("  AppId: `"$($Config.Application.AppId)`"")
    $lines.Add("  SpObjectId: `"$($Config.Application.SpObjectId)`"")
    $lines.Add("  DisplayName: `"$($Config.Application.DisplayName)`"")
    $lines.Add('')
    $lines.Add('Rbac:')
    $lines.Add('  Roles:')
    foreach ($role in @($Config.Rbac.Roles)) {
        $lines.Add("    - $role")
    }
    $lines.Add("  AccessGroupType: $($Config.Rbac.AccessGroupType)")
    $lines.Add("  GroupPrefix: $($Config.Rbac.GroupPrefix)")
    $lines.Add("  AccessGroupName: `"$($Config.Rbac.AccessGroupName)`"")
    $lines.Add('  Members:')
    foreach ($member in @($Config.Rbac.Members)) {
        $lines.Add("    - $member")
    }
    $lines.Add("  ManagedBy: $($Config.Rbac.ManagedBy)")
    $lines.Add("  BootstrapMember: $($Config.Rbac.BootstrapMember)")

    return $lines -join [System.Environment]::NewLine
}
