function ConvertTo-RBAC4AppYaml {
    param(
        [Parameter(Mandatory)]
        [psobject] $Config
    )

    function ConvertTo-RBAC4AppYamlScalar {
        param(
            [AllowNull()]
            [object] $Value
        )

        $text = if ($null -eq $Value) { '' } else { [string]$Value }
        if ($text -match "[`r`n]") {
            throw 'YAML scalar values cannot contain CR or LF characters.'
        }

        $escaped = $text.Replace('\', '\\').Replace('"', '\"')
        return '"' + $escaped + '"'
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# RBAC4App configuration — generated by New-RBAC4AppConfig')
    $lines.Add('# Feed to Invoke-RBAC4AppConfig in a session with only ExchangeOnlineManagement connected.')
    $lines.Add("SchemaVersion: $(ConvertTo-RBAC4AppYamlScalar $Config.SchemaVersion)")
    $lines.Add("GeneratedAt: $(ConvertTo-RBAC4AppYamlScalar $Config.GeneratedAt)")
    $lines.Add("TenantId: $(ConvertTo-RBAC4AppYamlScalar $Config.TenantId)")
    $lines.Add('')
    $lines.Add('Application:')
    $lines.Add("  AppId: $(ConvertTo-RBAC4AppYamlScalar $Config.Application.AppId)")
    $lines.Add("  SpObjectId: $(ConvertTo-RBAC4AppYamlScalar $Config.Application.SpObjectId)")
    $lines.Add("  DisplayName: $(ConvertTo-RBAC4AppYamlScalar $Config.Application.DisplayName)")
    $lines.Add('')
    $lines.Add('Rbac:')
    $lines.Add('  Roles:')
    foreach ($role in @($Config.Rbac.Roles)) {
        $lines.Add("    - $(ConvertTo-RBAC4AppYamlScalar $role)")
    }
    $lines.Add('')
    $lines.Add('RbacScope:')
    $lines.Add("  AccessGroupType: $(ConvertTo-RBAC4AppYamlScalar $Config.RbacScope.AccessGroupType)")
    $lines.Add("  GroupPrefix: $(ConvertTo-RBAC4AppYamlScalar $Config.RbacScope.GroupPrefix)")
    $lines.Add("  AccessGroupName: $(ConvertTo-RBAC4AppYamlScalar $Config.RbacScope.AccessGroupName)")
    $lines.Add('  Members:')
    foreach ($member in @($Config.RbacScope.Members)) {
        $lines.Add("    - $(ConvertTo-RBAC4AppYamlScalar $member)")
    }
    $lines.Add('  ManagedBy:')
    foreach ($owner in @($Config.RbacScope.ManagedBy)) {
        $lines.Add("    - $(ConvertTo-RBAC4AppYamlScalar $owner)")
    }
    $lines.Add("  BootstrapMember: $(ConvertTo-RBAC4AppYamlScalar $Config.RbacScope.BootstrapMember)")

    return $lines -join [System.Environment]::NewLine
}
