#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }

BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '..' 'src' 'EXORBACforAppManagement' 'EXORBACforAppManagement.psd1') -Force

    function global:Get-UnifiedGroup { }
    function global:New-UnifiedGroup { }
    function global:Set-UnifiedGroup { }
    function global:Add-UnifiedGroupLinks { }
    function global:Get-Recipient { }
    function global:New-ServicePrincipal { }
    function global:New-ManagementRoleAssignment { }

    $script:testYaml = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "1.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send
  AccessGroupType: M365Group
  GroupPrefix: Um365RAo1
  AccessGroupName: ""
  Members:
    - shared@contoso.com
  ManagedBy: GraphAPI-Dummy-owner
  BootstrapMember: GraphAPI-Dummy
'@
    $script:configPath = Join-Path $TestDrive 'test-config.yml'
    Set-Content $script:configPath -Value $script:testYaml -Encoding UTF8
}

AfterAll {
    Remove-Module EXORBACforAppManagement -Force -ErrorAction SilentlyContinue
    foreach ($n in 'Get-UnifiedGroup', 'New-UnifiedGroup', 'Set-UnifiedGroup', 'Add-UnifiedGroupLinks',
                   'Get-Recipient', 'New-ServicePrincipal', 'New-ManagementRoleAssignment') {
        Remove-Item "Function:\global:$n" -ErrorAction SilentlyContinue
    }
}

Describe 'Invoke-RBAC4AppConfig' {
    BeforeEach {
        Mock -ModuleName EXORBACforAppManagement Get-UnifiedGroup { }
        Mock -ModuleName EXORBACforAppManagement New-UnifiedGroup { [pscustomobject]@{ DisplayName = 'g'; Alias = 'g' } }
        Mock -ModuleName EXORBACforAppManagement Set-UnifiedGroup { }
        Mock -ModuleName EXORBACforAppManagement Add-UnifiedGroupLinks { }
        Mock -ModuleName EXORBACforAppManagement Get-Recipient { [pscustomobject]@{ PrimarySmtpAddress = 'shared@contoso.com' } }
        Mock -ModuleName EXORBACforAppManagement New-ServicePrincipal { [pscustomobject]@{ DisplayName = 'Contoso_SP' } }
        Mock -ModuleName EXORBACforAppManagement New-ManagementRoleAssignment { [pscustomobject]@{ Name = 'AppMailSend-Contoso' } }
    }

    It 'provisions scope group, registers SP, and creates role assignment from YAML' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        $res.ResolvedDisplay | Should -Be 'Contoso'
        $res.AppId            | Should -Be '11111111-1111-1111-1111-111111111111'
        $res.SpObjectId       | Should -Be '22222222-2222-2222-2222-222222222222'
        $res.Errors           | Should -BeNullOrEmpty
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 1
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ServicePrincipal -Times 1
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 1
    }

    It 'adds members via Add-UnifiedGroupLinks for M365Group and tracks them in MembersAdded' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName Add-UnifiedGroupLinks -Times 1
        $res.MembersAdded | Should -Contain 'shared@contoso.com'
    }

    It 'normalises the role name from the YAML' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        $res.RolesNormalized | Should -Contain 'Application Mail.Send'
    }

    It 'does not call mutating commands under -WhatIf' {
        $null = Invoke-RBAC4AppConfig -Path $script:configPath -WhatIf
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup          -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName Add-UnifiedGroupLinks     -Times 0
    }

    It 'records an error when the config file does not exist' {
        $err = $null
        $null = Invoke-RBAC4AppConfig -Path "$TestDrive\nonexistent.yml" -Confirm:$false -ErrorVariable err -ErrorAction SilentlyContinue
        $err | Should -Not -BeNullOrEmpty
    }

    It 'round-trips through ConvertTo/ConvertFrom yaml helpers correctly' {
        InModuleScope EXORBACforAppManagement {
            $config = [pscustomobject]@{
                SchemaVersion = '1.0'
                GeneratedAt   = '2026-09-20T10:00:00.0000000Z'
                TenantId      = 'tid-abc'
                Application   = [pscustomobject]@{
                    AppId       = 'aaa-bbb'
                    SpObjectId  = 'ccc-ddd'
                    DisplayName = 'My App'
                }
                Rbac = [pscustomobject]@{
                    Roles           = @('Application Mail.Send', 'Application Calendars.Read')
                    AccessGroupType = 'DistributionList'
                    GroupPrefix     = 'UDLRAo1'
                    AccessGroupName = ''
                    Members         = @('user@contoso.com')
                    ManagedBy       = 'owner@contoso.com'
                    BootstrapMember = 'GraphAPI-Dummy'
                }
            }
            $yaml   = ConvertTo-RBAC4AppYaml -Config $config
            $parsed = ConvertFrom-RBAC4AppYaml -Content $yaml
            $parsed.Application.AppId          | Should -Be 'aaa-bbb'
            $parsed.Application.SpObjectId     | Should -Be 'ccc-ddd'
            $parsed.Application.DisplayName    | Should -Be 'My App'
            $parsed.TenantId                   | Should -Be 'tid-abc'
            $parsed.Rbac.AccessGroupType       | Should -Be 'DistributionList'
            $parsed.Rbac.GroupPrefix           | Should -Be 'UDLRAo1'
            $parsed.Rbac.Roles                 | Should -Contain 'Application Mail.Send'
            $parsed.Rbac.Roles                 | Should -Contain 'Application Calendars.Read'
            $parsed.Rbac.Members               | Should -Contain 'user@contoso.com'
        }
    }
}
