#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }

BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '..' 'src' 'EXORBACforAppManagement' 'EXORBACforAppManagement.psd1') -Force

    function global:Get-UnifiedGroup { }
    function global:Get-UnifiedGroupLinks { }
    function global:New-UnifiedGroup { param($DisplayName, $Name, $Alias, $AccessType, [string[]]$ManagedBy, $Members) }
    function global:Set-UnifiedGroup { }
    function global:Add-UnifiedGroupLinks { }
    function global:Get-Recipient { }
    function global:New-ServicePrincipal { }
    function global:Get-ServicePrincipal { }
    function global:New-ManagementRoleAssignment { }
    function global:Get-ManagementRoleAssignment { }
    function global:Get-DistributionGroupMember { }

    $script:testYaml = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "3.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send

RbacScope:
  AccessGroupType: M365Group
  GroupPrefix: Um365RAo1
  AccessGroupName: ""
  Members:
    - shared@contoso.com
  ManagedBy:
    - GraphAPI-Dummy-owner
  BootstrapMember: GraphAPI-Dummy
'@
    $script:configPath = Join-Path $TestDrive 'test-config.yml'
    Set-Content $script:configPath -Value $script:testYaml -Encoding UTF8

    $script:testYamlOnPrem = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "3.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send

RbacScope:
  AccessGroupType: MailEnabledSecurityGroup
  GroupPrefix: Um365RAo1
  AccessGroupName: "OnPrem-Scope"
  Members:
    - shared@contoso.com
  ManagedBy:
    - custom-owner@contoso.com
  BootstrapMember: custom-bootstrap@contoso.com
'@
    $script:configPathOnPrem = Join-Path $TestDrive 'test-config-onprem.yml'
    Set-Content $script:configPathOnPrem -Value $script:testYamlOnPrem -Encoding UTF8

    $script:testYamlOldSchema = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "1.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send
  AccessGroupType: M365Group
  GroupPrefix: Um365RAo1
  AccessGroupName: ""
  Members:
    - shared@contoso.com
  ManagedBy: GraphAPI-Dummy-owner
  BootstrapMember: GraphAPI-Dummy
'@
    $script:configPathOldSchema = Join-Path $TestDrive 'test-config-old-schema.yml'
    Set-Content $script:configPathOldSchema -Value $script:testYamlOldSchema -Encoding UTF8

    $script:testYamlSchema2 = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "2.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send

RbacScope:
  AccessGroupType: M365Group
  GroupPrefix: Um365RAo1
  AccessGroupName: ""
  Members:
    - shared@contoso.com
  ManagedBy: GraphAPI-Dummy-owner
  BootstrapMember: GraphAPI-Dummy
'@
    $script:configPathSchema2 = Join-Path $TestDrive 'test-config-schema-2.yml'
    Set-Content $script:configPathSchema2 -Value $script:testYamlSchema2 -Encoding UTF8

    $script:testYamlMultiOwner = @'
# RBAC4App configuration — generated by New-RBAC4AppConfig
SchemaVersion: "3.0"
GeneratedAt: "2026-09-20T10:00:00Z"
TenantId: "tenant-123"

Application:
  AppId: "11111111-1111-1111-1111-111111111111"
  SpObjectId: "22222222-2222-2222-2222-222222222222"
  DisplayName: "Contoso"

Rbac:
  Roles:
    - Application Mail.Send

RbacScope:
  AccessGroupType: M365Group
  GroupPrefix: Um365RAo1
  AccessGroupName: ""
  Members:
    - shared@contoso.com
  ManagedBy:
    - owner1@contoso.com
    - owner2@contoso.com
  BootstrapMember: GraphAPI-Dummy
'@
    $script:configPathMultiOwner = Join-Path $TestDrive 'test-config-multi-owner.yml'
    Set-Content $script:configPathMultiOwner -Value $script:testYamlMultiOwner -Encoding UTF8

    # Same content as $script:testYaml, serialized as JSON instead.
    $script:testJsonConfig = [pscustomobject]@{
        SchemaVersion = '3.0'
        GeneratedAt   = '2026-09-20T10:00:00Z'
        TenantId      = 'tenant-123'
        Application   = [pscustomobject]@{
            AppId       = '11111111-1111-1111-1111-111111111111'
            SpObjectId  = '22222222-2222-2222-2222-222222222222'
            DisplayName = 'Contoso'
        }
        Rbac          = [pscustomobject]@{ Roles = @('Application Mail.Send') }
        RbacScope     = [pscustomobject]@{
            AccessGroupType = 'M365Group'
            GroupPrefix     = 'Um365RAo1'
            AccessGroupName = ''
            Members         = @('shared@contoso.com')
            ManagedBy       = @('GraphAPI-Dummy-owner')
            BootstrapMember = 'GraphAPI-Dummy'
        }
    }
    $script:configPathJson = Join-Path $TestDrive 'test-config.json'
    $script:testJsonConfig | ConvertTo-Json -Depth 6 | Set-Content $script:configPathJson -Encoding UTF8

    $script:configPathJsonBadExtension = Join-Path $TestDrive 'test-config-json-as-yml.yml'
    $script:testJsonConfig | ConvertTo-Json -Depth 6 | Set-Content $script:configPathJsonBadExtension -Encoding UTF8

    Set-Content (Join-Path $TestDrive 'test-config-malformed.json') -Value '{ not valid json' -Encoding UTF8
    $script:configPathMalformedJson = Join-Path $TestDrive 'test-config-malformed.json'
}

AfterAll {
    Remove-Module EXORBACforAppManagement -Force -ErrorAction SilentlyContinue
    foreach ($n in 'Get-UnifiedGroup', 'Get-UnifiedGroupLinks', 'New-UnifiedGroup', 'Set-UnifiedGroup', 'Add-UnifiedGroupLinks',
                   'Get-Recipient', 'New-ServicePrincipal', 'Get-ServicePrincipal', 'New-ManagementRoleAssignment', 'Get-ManagementRoleAssignment', 'Get-DistributionGroupMember') {
        Remove-Item "Function:\global:$n" -ErrorAction SilentlyContinue
    }
}

Describe 'Invoke-RBAC4AppConfig' {
    BeforeEach {
        Mock -ModuleName EXORBACforAppManagement Get-UnifiedGroup { }
        Mock -ModuleName EXORBACforAppManagement Get-UnifiedGroupLinks { @() }
        Mock -ModuleName EXORBACforAppManagement New-UnifiedGroup { [pscustomobject]@{ DisplayName = 'g'; Alias = 'g' } }
        Mock -ModuleName EXORBACforAppManagement Set-UnifiedGroup { }
        Mock -ModuleName EXORBACforAppManagement Add-UnifiedGroupLinks { }
        Mock -ModuleName EXORBACforAppManagement Get-Recipient { [pscustomobject]@{ PrimarySmtpAddress = 'shared@contoso.com' } }
        Mock -ModuleName EXORBACforAppManagement Get-DistributionGroupMember { @() }
        Mock -ModuleName EXORBACforAppManagement Get-ServicePrincipal { @() }
        Mock -ModuleName EXORBACforAppManagement New-ServicePrincipal { [pscustomobject]@{ DisplayName = 'Contoso_SP' } }
        Mock -ModuleName EXORBACforAppManagement New-ManagementRoleAssignment { [pscustomobject]@{ Name = 'AppMailSend-Contoso' } }
        Mock -ModuleName EXORBACforAppManagement Get-ManagementRoleAssignment { }
    }

    It 'provisions scope group, registers SP, and creates role assignment from YAML' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        $res.ResolvedDisplay | Should -Be 'Contoso'
        $res.AppId            | Should -Be '11111111-1111-1111-1111-111111111111'
        $res.SpObjectId       | Should -Be '22222222-2222-2222-2222-222222222222'
        $res.Errors           | Should -BeNullOrEmpty
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 1
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ServicePrincipal -Times 1
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 1
    }

    It 'adds members via Add-UnifiedGroupLinks for M365Group and tracks them in MembersAdded' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName Add-UnifiedGroupLinks -Times 1
        $res.MembersAdded | Should -Contain 'shared@contoso.com'
    }

    It 'normalises the role name from the YAML' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false
        $res.RolesNormalized | Should -Contain 'Application Mail.Send'
    }

    It 'reports the pre-existing and newly-added members in MembersFinal' {
        Mock -ModuleName EXORBACforAppManagement Get-UnifiedGroupLinks { @([pscustomobject]@{ PrimarySmtpAddress = 'existing@contoso.com'; Name = 'existing' }) }

        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false

        $res.MembersFinal | Should -Contain 'existing@contoso.com'
        $res.MembersFinal | Should -Contain 'shared@contoso.com'
    }

    It 'skips creating a role assignment that already exists and is scoped to the target group' {
        Mock -ModuleName EXORBACforAppManagement Get-ManagementRoleAssignment {
            [pscustomobject]@{ Name = 'AppMailSend-Contoso'; Role = 'Application Mail.Send'; RecipientWriteScope = 'Group'; CustomRecipientWriteScope = $null; CustomResourceScope = 'Um365RAo1-Contoso_20d5848c-4d61-4b82-a44f-205adc37321f' }
        }

        $res = Invoke-RBAC4AppConfig -Path $script:configPath -Confirm:$false

        $res.RoleAssignments | Should -HaveCount 1
        ($res.Warnings -join ';') | Should -Match 'already exists and is scoped'
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 0
    }

    It 'does not call mutating commands under -WhatIf' {
        $null = Invoke-RBAC4AppConfig -Path $script:configPath -WhatIf
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup          -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName Add-UnifiedGroupLinks     -Times 0
    }

    It 'auto-detects JSON from a .json extension and provisions the same as the equivalent YAML' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPathJson -Confirm:$false

        $res.ResolvedDisplay | Should -Be 'Contoso'
        $res.AppId           | Should -Be '11111111-1111-1111-1111-111111111111'
        $res.SpObjectId      | Should -Be '22222222-2222-2222-2222-222222222222'
        $res.Errors          | Should -BeNullOrEmpty
        $res.MembersAdded    | Should -Contain 'shared@contoso.com'
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 1
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 1
    }

    It '-Format Json forces JSON parsing even with a non-.json extension' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPathJsonBadExtension -Format Json -Confirm:$false

        $res.ResolvedDisplay | Should -Be 'Contoso'
        $res.Errors          | Should -BeNullOrEmpty
    }

    It 'records an error instead of throwing for malformed JSON' {
        $err = $null
        $null = Invoke-RBAC4AppConfig -Path $script:configPathMalformedJson -Confirm:$false -ErrorVariable err -ErrorAction SilentlyContinue
        $err -join ';' | Should -Match 'could not be parsed as Json'
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 0
    }

    It 'records an error when the config file does not exist' {
        $err = $null
        $null = Invoke-RBAC4AppConfig -Path "$TestDrive\nonexistent.yml" -Confirm:$false -ErrorVariable err -ErrorAction SilentlyContinue
        $err | Should -Not -BeNullOrEmpty
    }

    It 'records an error and does not provision anything for a pre-2.0 schema config' {
        $err = $null
        $null = Invoke-RBAC4AppConfig -Path $script:configPathOldSchema -Confirm:$false -ErrorVariable err -ErrorAction SilentlyContinue
        $err -join ';' | Should -Match "SchemaVersion '1.0'"
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 0
    }

    It 'records an error and does not provision anything for a 2.0 schema config (scalar ManagedBy, pre-multi-owner)' {
        $err = $null
        $null = Invoke-RBAC4AppConfig -Path $script:configPathSchema2 -Confirm:$false -ErrorVariable err -ErrorAction SilentlyContinue
        $err -join ';' | Should -Match "SchemaVersion '2.0'"
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 0
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-ManagementRoleAssignment -Times 0
    }

    It 'provisions the scope group with multiple owners from a multi-value ManagedBy list' {
        Mock -ModuleName EXORBACforAppManagement Get-Recipient {
            param($Identity)
            [pscustomobject]@{ PrimarySmtpAddress = $Identity }
        }

        $null = Invoke-RBAC4AppConfig -Path $script:configPathMultiOwner -Confirm:$false

        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName New-UnifiedGroup -Times 1 -ParameterFilter {
            (Compare-Object $ManagedBy @('owner1@contoso.com', 'owner2@contoso.com')).Count -eq 0
        }
    }

    It 'MailEnabledSecurityGroup: warns that Members, ManagedBy, and BootstrapMember from config are ignored' {
        $res = Invoke-RBAC4AppConfig -Path $script:configPathOnPrem -Confirm:$false
        ($res.Warnings -join ';') | Should -Match 'Membership of MailEnabledSecurityGroup .* was ignored'
        ($res.Warnings -join ';') | Should -Match 'ManagedBy from config was ignored'
        ($res.Warnings -join ';') | Should -Match 'BootstrapMember from config was ignored'
        Should -Invoke -ModuleName EXORBACforAppManagement -CommandName Add-UnifiedGroupLinks -Times 0
    }

    It 'round-trips through ConvertTo/ConvertFrom yaml helpers correctly' {
        InModuleScope EXORBACforAppManagement {
            $config = [pscustomobject]@{
                SchemaVersion = '3.0'
                GeneratedAt   = '2026-09-20T10:00:00.0000000Z'
                TenantId      = 'tid-abc'
                Application   = [pscustomobject]@{
                    AppId       = 'aaa-bbb'
                    SpObjectId  = 'ccc-ddd'
                    DisplayName = 'My App'
                }
                Rbac = [pscustomobject]@{
                    Roles = @('Application Mail.Send', 'Application Calendars.Read')
                }
                RbacScope = [pscustomobject]@{
                    AccessGroupType = 'DistributionList'
                    GroupPrefix     = 'UDLRAo1'
                    AccessGroupName = ''
                    Members         = @('user@contoso.com')
                    ManagedBy       = @('owner1@contoso.com', 'owner2@contoso.com')
                    BootstrapMember = 'GraphAPI-Dummy'
                }
            }
            $yaml   = ConvertTo-RBAC4AppYaml -Config $config
            $parsed = ConvertFrom-RBAC4AppYaml -Content $yaml
            $parsed.Application.AppId          | Should -Be 'aaa-bbb'
            $parsed.Application.SpObjectId     | Should -Be 'ccc-ddd'
            $parsed.Application.DisplayName    | Should -Be 'My App'
            $parsed.TenantId                   | Should -Be 'tid-abc'
            $parsed.RbacScope.AccessGroupType  | Should -Be 'DistributionList'
            $parsed.RbacScope.GroupPrefix      | Should -Be 'UDLRAo1'
            $parsed.Rbac.Roles                 | Should -Contain 'Application Mail.Send'
            $parsed.Rbac.Roles                 | Should -Contain 'Application Calendars.Read'
            $parsed.RbacScope.Members          | Should -Contain 'user@contoso.com'
            $parsed.RbacScope.ManagedBy        | Should -Contain 'owner1@contoso.com'
            $parsed.RbacScope.ManagedBy        | Should -Contain 'owner2@contoso.com'
        }
    }
}
